image: ubuntu:16.04

before_script:
  - apt-get update

  # installing tzdata pkg is a workaround to Ubuntu messing up with deps in STABLE/LTS
  # bug: https://bugzilla.xamarin.com/show_bug.cgi?id=56499
  # downstream fix: https://anonscm.debian.org/cgit/pkg-mono/packages/mono.git/commit/?id=4d0e950
  # upstream fix: https://github.com/mono/mono/commit/940944dcdefb56f7952cd35a43bcbd5f70ba78ef
  - apt-get install -y tzdata

  - apt-get install -y curl
  - apt-get install -y nuget mono-complete mono-xbuild fsharp

stages:
  - core-build
  - test
  - frontend-build

core-build:
  stage: core-build
  script:
    - time (./configure.sh && make && make install)

test:
  stage: test
  script:
    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

frontend-build:
  stage: frontend-build
  script:
    # taken from https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current
    - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    - mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    - sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
    - apt-get install -y apt-transport-https
    - apt-get update
    - apt-get install -y dotnet-sdk-2.1.101
    - apt-get install -y dotnet-runtime-2.0.6

    # taken from http://www.mono-project.com/download/stable/#download-lin
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    - apt-get update
    - apt-get install -y mono-devel
    - msbuild /verbosity:detailed gwallet.frontend.linux.sln
